config/routes.rb
Rails.application.routes.draw do
  root "welcome_v1#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tags, only: %i(index show)

  resources :questions do
    member do
      post :question_like_up
      post :question_like_down
    end
    collection do
      get :search
      get :public_replyers
      get :show_replyer
    end

    resources :answers
  end

  resources :welcome_test, only: %i(index)

  resources :welcome_v1, only: %i(index)

  resources :guides do
    collection do
      get :tags_guide
      get :replyers_guide
      get :faq
      get :about
      get :contact
    end
  end

  # devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }

  # namespace for account
  namespace :account do
    resources :blogs do
      member do
        get :ta_blogs
      end
    end

    resources :tags do
      member do
        post :cancel
        post :add_tag
      end
    end

    resources :answers do
      member do
        post :publish_hidden
        post :subscribe_answers
      end
    end

    resources :questions do
      member do
        post :to_downpayment
        post :publish_hidden
        post :cancel
        post :reopen
        patch :refine_reward
        get :my_favorite_questions
      end
      collection do
        get :invitated_questions
      end
    end

    resources :users do
      member do
        get :new_image
        get :create_image
        get :new_profile
        get :edit_profile
        put :update_profile
        get :show_profile
        get :index_profile
        get :my_questions_answers
        get :wallet
        # add withdraw actions
        get :withdraw_edit
        post :withdraw_change
        get :deposit_edit
        post :deposit_change
        get :exhibition_profile
        get :my_subscriptions
        # 显示我的关注
        get :follow_show
        post :submit_application
        post :add_tags
        get :reply
      end

      collection do
        get :replyers
        get :show_profile
      end
    end

    resources :follows, only: %i(like unlike) do
      member do
        post :like
        post :unlike
      end
    end
  end

  # namespace for admin
  namespace :admin do
    resources :users do
      member do
        post :change_to_admin
        post :change_to_user
        post :approved
      end
    end

    resources :questions do
      member do
        post :hide
        post :publish
      end
    end

    resources :answers do
      member do
        post :hide
        post :publish
      end
    end

    resources :admins do
      collection do
        get :bill
      end
    end

    resources :tags
  end

  # 站内信
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # vote功能
  namespace :vote do
    # 对answer的vote
    resources :vote_answers, only: %i(like,like_cancel,unlike,unlike_cancel) do
      member do
        post :like
        post :unlike
      end
    end
  end
end

app/controllers/welcome_test_controller.rb
class WelcomeTestController < ApplicationController
  layout "welcome_test"
  layout:false,only: [:register_guide]

  def index
    # @questions = Question.all
    @questions = Question.limit(6)

    # 记录上一次请求路径是否是登录或者注册
    flag = request.referer && request.referer.include?("/users/sign_up")

    # 注册页进入guide页面
    if flag
      redirect_to tags_guide_guides_path
      return
    end

    flag = request.referer && request.referer.include?("/users/sign_in")

    # 如果上次请求是登录或注册，直接跳入首页。
    if flag & current_user
      if current_user.admin?
        redirect_to admin_admins_path
      else
        redirect_to show_profile_account_user_path(current_user)
      end
    end
  end

end

app/helpers/welcome_test_helper.rb
module WelcomeTestHelper
end

app/views/welcome_test/_about_us.html.erb
<div class="container">
  <div class="row">

      <div class="col-md-3 col-md-offset-2 col-sm-4 col-xs-12">
          <div class="pull-left about-us-icon">
              <img src="/index/icon_key.png"/>
          </div>
          <div class="bottom-gap col-md-9 col-sm-9 col-xs-10 ">
            <strong><span class="about-us-title">知识变现</span><br/></strong>
            <span class="about-us-text">留学多年，宝贵的知识可以大量变现哦！</span>
          </div>
      </div>

      <div class="col-md-3  col-sm-4 col-xs-12">
        <div class="pull-left about-us-icon">
            <img src="/index/icon_up.png"/>
        </div>
        <div class="bottom-gap col-md-9 col-sm-9 col-xs-10">
          <strong><span class="about-us-title">提高声誉</span><br/></strong>
          <span class="about-us-text">分享带来声望，认识学弟学妹，做留学网红。</span>
        </div>
      </div>

      <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="pull-left about-us-icon">
              <img src="/index/icon_light.png"/>
          </div>
          <div class="bottom-gap col-md-9 col-sm-9 col-xs-10">
            <strong><span class="about-us-title">收支透明</span><br/></strong>
            <span class="about-us-text">账户余额快速提现，安全有保障。</span>
          </div>
      </div>

  </div>
</div>

app/views/welcome_test/_banner.html.erb
<section class="banner">
  <div class="banner banner-image">
    <img src="index/banner1.jpg", class="banner-image" />

  </div>

<!-- banner 蒙板及上面内容 -->
  <div class="banner dark-bg">
    <img src="/logo.png" class="logo"/>
    <div class="banner-font">
      <div class="line"></div>
      <h1>学霸在线</h1>
      <h3>提高声誉，即刻赚钱</h3>
    </div>

    <!-- 添加searchbar -->
    <div class="search-bar">
      <%= render "questions/search_bar" %>
    </div>
  </div>
</section>

app/views/welcome_test/_banner_slide.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="">
        <img src="index/1.jpg" alt="..." class="banner-image" />
      </div>

      <div class="banner dark-bg">
        <img src="/logo.png" class="logo"/>
        <div class="banner-font">
          <div class="line"></div>
          <h1>学霸在线</h1>
          <h3>提高声誉，即刻赚钱</h3>
        </div>

        <!-- 添加searchbar -->
        <div class="search-bar">
          <%= render "questions/search_bar" %>
        </div>
      </div>
    </div>

    <div class="item">
      <div class="">
        <img src="index/3.jpg" alt="..." class="banner-image"/>
      </div>
      <div class="banner dark-bg2">

        <div class="banner-font">
          <h1>注册就送1000积分！</h1><br />
          <%= link_to("马上注册",new_user_registration_path, class:"btn btn-lg btn-danger") %>
        </div>
      </div>
    </div>

  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome_test/_banner_slide2.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="banner-image" style="background:url(index/1.jpg) center;">
      </div>

      <div class="banner">
        <img src="/logo.png" class="logo"/>
        <div class="banner-font">
          <div class="line"></div>
          <h1>学霸在线</h1>
          <h3>提高声誉，即刻赚钱</h3>
        </div>

        <!-- 添加searchbar -->
        <div class="search-bar">
          <%= render "questions/search_bar" %>
        </div>
      </div>
    </div>

    <div class="item">
      <div class="banner-image" style="background:url(index/3.jpg) center;">

      </div>
      <div class="banner dark-bg2">

        <div class="banner-font">
          <h1>注册就送1000积分！</h1><br />
          <%= link_to("马上注册",new_user_registration_path, class:"btn btn-lg btn-danger") %>
        </div>
      </div>
    </div>

  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/welcome_test/_bottom_banner.html.erb
<section class="bottom-banner hidden-xs" style="background:url(index/bottom-banner.jpeg) center;">

    <div class="bottom-banner-font col-md-4 col-md-offset-1 col-sm-6 col-sm-offset-1 col-xs-10 col-xs-offset-0">
      <h3>我是La Trobe University 的學生, 暑假後升讀year 2。</h3>
      <h4>从挑学校到最终拿到offer,花费了很多不必要的时间和金钱。<br/>
      现在把自己的经验分享出来，帮助学弟学妹少走弯路。</h4>
      <%= link_to('马上提问', new_account_question_path, class: "btn btn-lg btn-danger")  %>
    </div>

</section>

app/views/welcome_test/_hot_question.html.erb
<div class="container">
  <div class="row">
    <% @questions.each do |question| %>
      <div class="col-sm-6 col-sx-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title" style="display : inline"><%= question.title %></h3>
            <%= link_to(question_like_up_question_path(question), method: :post) do %>
              <button type="button" class="btn btn-default" aria-label="Left Align">
                <span><%= question.question_likes.count %> </span>
                <span class="fa fa-thumbs-o-up" aria-hidden="true"></span>
              </button>
            <% end %>
          </div>
          <div class="panel-body">
            <p><%= sanitize(question.description).truncate(30) %></p>
            <div class="pull-right">
              <%= render_head_image_30(question.user) %>
              <!-- <%= gravatar_tag question.user.email, :size => 40, :default => avatar_url %> -->
            </div>
            <br>
            <p>回答人数：<%= question.answers.count %></p>
            <hr>
            <div>
              <div class="pull-left">

                <span class="glyphicon glyphicon-tags" aria-hidden="true"> <%= render question.tags %></span>

              </div>
              <div class="pull-right">
                悬赏金额: <%= question.downpayment %>
                <%= link_to '问题详情', question, class: "btn btn-default" %>
                <%= link_to '我要回答', new_question_answer_path(question), class: "btn btn-danger" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome_test/_hot_question_section_title.html.erb
<div class="container section-title">
  <div class="row text-center">
    <div class="col-md-2 col-md-offset-3 col-sm-3 col-sm-offset-1  col-xs-3">
      <img src="/index/leafing-left.png"/>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6">
      <strong><span class="text-danger" style="font-size:18px">最热悬赏问题</span></strong>
    </div>
    <div class="col-md-2 col-sm-3 col-xs-3">
      <img src="/index/leafing-right.png"/>
    </div>
  </div>
</div>

app/views/welcome_test/_picture_list.html.erb
<div class="container">
  <div class="row picture-center hidden-sm">
      <div class=" hidden-sm hidden-xs">
          <div class="pull-left">
            <%= link_to(new_user_registration_path) do %>
            <img src="/replyer1.png"/>
            <div class="picture-mask">
                <span>成为学霸</span>
            </div>
            <% end %>
          </div>
          <div class="pull-left">
            <%= link_to(new_account_question_path) do %>
            <img src="/replyer2.png"/>
            <div class="picture-mask">
              <span>马上提问</span>
            </div>
            <% end %>
          </div>

          <div class="pull-left">
              <%= link_to(new_account_question_path) do %>
              <img src="/replyer3.png"/>
              <div class="picture-mask">
                <span>问题海淘</span>
              </div>
            <% end %>
          </div>
          <div class="pull-left">
              <%= link_to(new_account_question_path) do %>
                <img src="/replyer4.png"/>
                <div class="picture-mask">
                  <span>寻找学霸</span>
                </div>
              <% end %>
          </div>

      </div>
  </div>
</div>

app/views/welcome_test/_question_list.html.erb
<section class="question-list">
  <%= render "hot_question_section_title" %>
  <%= render "hot_question" %>
</section>

app/views/welcome_test/index.html.erb
<%= render "banner_slide2" %>

<%= render "picture_list" %>

<div style="height:30px"></div>

<%= render "about_us" %>

<%= render "question_list" %>

<%= render "bottom_banner" %>