config/routes.rb
Rails.application.routes.draw do
  root "welcome_v1#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tags, only: %i(index show)

  resources :questions do
    member do
      post :question_like_up
      post :question_like_down
    end
    collection do
      get :search
      get :public_replyers
      get :show_replyer
    end

    resources :answers
  end

  resources :welcome_test, only: %i(index)

  resources :welcome_v1, only: %i(index)

  resources :guides do
    collection do
      get :tags_guide
      get :replyers_guide
      get :faq
      get :about
      get :contact
    end
  end

  # devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }

  # namespace for account
  namespace :account do
    resources :blogs do
      member do
        get :ta_blogs
      end
    end

    resources :tags do
      member do
        post :cancel
        post :add_tag
      end
    end

    resources :answers do
      member do
        post :publish_hidden
        post :subscribe_answers
      end
    end

    resources :questions do
      member do
        post :to_downpayment
        post :publish_hidden
        post :cancel
        post :reopen
        patch :refine_reward
        get :my_favorite_questions
      end
      collection do
        get :invitated_questions
      end
    end

    resources :users do
      member do
        get :new_image
        get :create_image
        get :new_profile
        get :edit_profile
        put :update_profile
        get :show_profile
        get :index_profile
        get :my_questions_answers
        get :wallet
        # add withdraw actions
        get :withdraw_edit
        post :withdraw_change
        get :deposit_edit
        post :deposit_change
        get :exhibition_profile
        get :my_subscriptions
        # 显示我的关注
        get :follow_show
        post :submit_application
        post :add_tags
        get :reply
      end

      collection do
        get :replyers
        get :show_profile
      end
    end

    resources :follows, only: %i(like unlike) do
      member do
        post :like
        post :unlike
      end
    end
  end

  # namespace for admin
  namespace :admin do
    resources :users do
      member do
        post :change_to_admin
        post :change_to_user
        post :approved
      end
    end

    resources :questions do
      member do
        post :hide
        post :publish
      end
    end

    resources :answers do
      member do
        post :hide
        post :publish
      end
    end

    resources :admins do
      collection do
        get :bill
      end
    end

    resources :tags
  end

  # 站内信
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # vote功能
  namespace :vote do
    # 对answer的vote
    resources :vote_answers, only: %i(like,like_cancel,unlike,unlike_cancel) do
      member do
        post :like
        post :unlike
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :question, counter_cache: true

  has_many :answer_subscriptions
  has_many :subscribed_users, through: :answer_subscriptions, source: :user
  has_many :like_answers
  # has_many :user_likes, through: :like_answers, source: :user
  has_many :unlike_answers

  # answer_status 字段 有3种状态 pending best_answer unchosen

  scope :published, -> { where(is_hidden: false) }

  def updated_at_formate
    updated_at.strftime("%Y-%m-%d %H:%M:%S")
  end

  def hide!
    self.is_hidden = true
    save
  end

  def publish!
    self.is_hidden = false
    save
  end

  def best_answer!
    self.answer_status = "best_answer"
    save
  end

  def make_others_unchosen!(question)
    question.answers.each do |answer|
      if answer.answer_status != "best_answer"
        answer.answer_status = "unchosen"
        answer.save
      end
    end
  end
end

# == Schema Information
#
# Table name: answers
#
#  id                         :integer          not null, primary key
#  content                    :text
#  is_hidden                  :boolean          default(FALSE)
#  user_id                    :integer
#  question_id                :integer
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#  answer_status              :string           default("pending")
#  answer_subscriptions_count :integer
#  created_on                 :date
#  updated_on                 :date
#  like_answers_count         :integer          default(0)
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#  index_answers_on_user_id      (user_id)
#

app/controllers/account/answers_controller.rb
class Account::AnswersController < AccountController
  before_action :set_answer, only: %i(show edit update destroy publish_hidden subscribe_answers)
  layout 'user_center', only: %i(index show edit)
  def index
    @answers = current_user.answers.published
    @answers = @answers.paginate(page: params[:page], per_page: 10)
    drop_breadcrumb("首页", show_profile_account_user_path(current_user))
    drop_breadcrumb("我回答的问题")
  end

  def show
    drop_breadcrumb("首页", show_profile_account_user_path(current_user))
    drop_breadcrumb("我回答的问题", account_answers_path(@answer))
    drop_breadcrumb("我的回答")
    @question = @answer.question
    @refer_questions = Question.published.where(status: "open").order("watches DESC").limit(3)
  end

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def edit
    @question = @answer.question
    @question.watches_counter!
    drop_breadcrumb("我回答的问题", account_answers_path(@answer))
    drop_breadcrumb("修改我的回答")
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.user = current_user
    @answer.question = @question

    if @answer.save
      redirect_to account_answer_path(@answer), notice: "回答已发送！"
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to account_answer_path(@answer), notice: "回答已更新！"
    else
      render :edit
    end
  end

  def publish_hidden
    is_hidden = params[:is_hidden]
    @answer.is_hidden =
      if is_hidden == "publish"
        false
      else
        true
      end

    if @answer.save
      flash[:notice] = "操作成功！"
    else
      flash[:alert] = "操作失败！"
    end

    redirect_to :back
  end

  def subscribe_answers
    if @answer.user == current_user
      flash[:alert] = "不能偷听自己的回答！"
      redirect_to :back
      return
    end
    if current_user.subscribed_answer?(@answer)
      flash[:alert] = "您已经购买过答案，可以直接偷听"
      redirect_to my_subscriptions_account_user_path(current_user)
      return
    end
    if current_user.subscribe!(@answer)
      @answer_subscription = @answer.answer_subscriptions.where(user_id: current_user).first
      @answer_subscription.payment_method = params[:answer_subscription][:payment_method]
      @answer_subscription.save
      RewardAnswerSubscription.new(current_user, @answer.user, @answer.question.user, @answer).perform!
      flash[:notice] = "可以偷听答案了！"
    else
      flash[:alert] = "偷听不成功"
    end
    redirect_to :back
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:content)
  end

  # def answer_subscription_params
  #   params.require(:answer_subscription).permit(:payment_method)
  # end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < AdminController
  def index
    @answers = Answer.all
    drop_breadcrumb("后台首页", admin_user_path(current_user))
    drop_breadcrumb("答案管理")
  end

  def show
    @answer = Answer.find(params[:id])
    drop_breadcrumb("后台首页", admin_user_path(current_user))
    drop_breadcrumb("答案管理", admin_answers_path)
    drop_breadcrumb(@answer.question.title)
  end

  def hide
    @answer = Answer.find(params[:id])
    @answer.hide!
    flash[:alert] = "你隐藏了回答#{@answer.content}"
    redirect_to :back
  end

  def publish
    @answer = Answer.find(params[:id])
    @answer.publish!
    flash[:alert] = "你公开了回答#{@answer.content}"
    redirect_to :back
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i(create new edit update destroy)
  before_action :check_question_and_require_not_self_reply, only: %i(new edit create update)
  before_action :set_answer, only: %i(show edit update destroy)
  layout 'user_center', only: %i(new)
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
    drop_breadcrumb(@question.title, question_path(@question))
    drop_breadcrumb("我要回答")
    @question.watches_counter!
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question
    unless current_user.gender && current_user.school && current_user.major
      current_user.gender = params[:gender].downcase if params[:gender]
      current_user.school = params[:school] if params[:school]
      current_user.major = params[:major] if params[:major]
      current_user.save
    end

    if @answer.save
      NotificationService.new(@question.user, current_user, @answer).send_notification!
      redirect_to account_answer_path(@answer), notice: "回答已发送！"
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = Answer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:content)
  end

  def check_question_and_require_not_self_reply
    @question = Question.find(params[:question_id])
    if @question.user == current_user
      flash[:warning] = "亲，不要回答自己的问题哦~"
      redirect_to :back
    end
  end

end

app/helpers/account/answers_helper.rb
module Account::AnswersHelper
  def render_user_auth?(user)
    current_user && current_user == user
  end

end

app/helpers/admin/answers_helper.rb
module Admin::AnswersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for [@question,@answer] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <% unless current_user.gender && current_user.school && current_user.major %>
      <div class="addtional-info-border">
          您还缺少一些个人资料，填写一下，答案更容易被偷听！
          <br>
        <% unless current_user.gender %>
          <h4>性别</h4>
          <%= select_tag "gender", options_for_select(["Male", "Female"], "Male"), class:"form-control form-group", id:"gender" %>
        <% end %>
        <% unless current_user.school %>
          <h4>学校：</h4>
          <%= tag("input", type: "text", name: "school", class: "form-control form-group") %>
        <% end %>
        <% unless current_user.major %>
          <h4>专业：</h4>
          <%= tag("input", type: "text", name: "major", class: "form-control form-group" )%>
        <% end %>
      </div>
    <% end %>

  </div>

  <div class="form-actions">
    <%= f.submit "提交回答", disable_with: "提交中……", class:"btn btn-primary"%>
  </div>
<% end %>

<%= content_for :handwrite_javascript do %>
<script type="text/javascript">
  var editor = new Simditor({
   textarea: $("#answer_content"),
   toolbar: ['title', 'bold', 'italic', 'underline', 'strikethrough', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', 'link', '|','hr','indent','outdent','alignment'],
   placeholder: '想问的问题...',
   upload: {
     fileKey: 'file',
     params: null,
     connectionCount: 3,
     leaveConfirm: 'Uploading is in progress, are you sure to leave this page?'
   }
  });
  editor.value();
</script>
<% end %>

app/views/answers/_question_info_sidebar.html.erb
<div class="col-xs-12 col-sm-3 col-md-3 col-lg-2">
  <div class="db-wrapper">
    <div class="db-pricing-seven">
      <ul>
        <li class="price">
          <i class="glyphicon glyphicon-yen"></i>
          悬赏 - <%= @question.downpayment %>
        </li>
        <li><i class="glyphicon glyphicon-fire"></i><%= @question.liking_users.count %>人也想听</li>
        <li><i class="glyphicon glyphicon-user"></i>提问者-<%= link_to @question.user.name, exhibition_profile_account_user_path(@question.user) %></li>
        <li><i class="glyphicon glyphicon-tags"></i>标签：<%= render @question.tags %></li>
        <li><i class="glyphicon glyphicon-edit"></i>已有回答<%= @question.answers.count %>个</li>
        <li><i class="glyphicon glyphicon-eye-open"></i>被浏览<%= @question.watches %>次</li>
      </ul>
    </div>
  </div>
</div>

app/views/answers/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="col-md-12">
<h4>我的回答</h4>

<table class="table">
  <thead>
    <tr>
      <th>回答内容</th>
      <!-- <th>Is hidden</th> -->
      <!-- <th>User</th> -->
      <!-- <th>Question</th> -->
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <!-- <td><%#= answer.is_hidden %></td> -->
        <!-- <td><%#= answer.user_id %></td> -->
        <!-- <td><%#= answer.question_id %></td> -->
        <!-- <td colspan="3"><%#= link_to '详情', answer %> |
        <%#= link_to '编辑', edit_answer_path(answer) %>
        <%#= link_to '删除', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <div class="total clearfix">
    <%#= link_to '我要回答', new_answer_path %>
    <%= link_to '我要回答', new_question_answer_path %>
    <!-- <span class="pull-right">
    </span> -->
  </div>
</div>

app/views/answers/new.html.erb
<ul class="list-group index-ul">
  <li class="list-group-item">
    <div class="media">
        <div class="media-body">
          <span class="media-meta pull-right"><%= @question.liking_users.count %>人也想听</span>
          <span class="media-meta pull-right" style="padding:0 5px;">|</span>
          <span class="media-meta pull-right" style="padding:0 5px;">悬赏: <%= @question.downpayment %></span>
          <p class="answers-new-font">
            提问者: <%= link_to @question.user.name, exhibition_profile_account_user_path(@question.user) %><br />
            <%= link_to(@question.title,account_question_path(@question)) %><br />
            <%= @question.description %>
          </p>

          <hr/>
        <p class="summary">
          <span class="media-meta pull-left" style="padding-right:20px">阅读数：<%= @question.watches %></span>
          <span class="media-meta pull-left" style="padding-right:20px">标签：<%= render @question.tags %></span>
          <!-- <span class="media-meta pull-left" style="padding-right:20px">已有回答<%= @question.answers.count %>个</span> -->
          <%= link_to("已有回答#{@question.answers.count}个",account_question_path(@question), class:"media-meta pull-left", style:"padding-right:20px") %>
          <span class="media-meta pull-left"><%= @question.created_on %></span>
        </p>
      </div>
    </div>
  </li>
</ul>
<h3>我要回答</h3>
<%= render "form" %>

app/views/answers/show.html.erb
<div class="col-md-12">
  <div class="panel panel-default ">
    <div class="panel-heading">
      <h3 class="panel-title">我的回答</h3>
    </div>

    <div class="panel-body">
      <p>
        <%= sanitize(@answer.content) %>
      </p>

    </div>

    <div class="total clearfix">
        <span class="pull-right">
          <%= link_to '编辑', edit_answer_path(@answer) %> |
          <%= link_to '返回', answers_path %>
        </span>
      </div>
  </div>
</div>