config/routes.rb
Rails.application.routes.draw do
  root "welcome_v1#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tags, only: %i(index show)

  resources :questions do
    member do
      post :question_like_up
      post :question_like_down
    end
    collection do
      get :search
      get :public_replyers
      get :show_replyer
    end

    resources :answers
  end

  resources :welcome_test, only: %i(index)

  resources :welcome_v1, only: %i(index)

  resources :guides do
    collection do
      get :tags_guide
      get :replyers_guide
      get :faq
      get :about
      get :contact
    end
  end

  # devise_for :users
  devise_for :users, controllers: { registrations: "registrations" }

  # namespace for account
  namespace :account do
    resources :blogs do
      member do
        get :ta_blogs
      end
    end

    resources :tags do
      member do
        post :cancel
        post :add_tag
      end
    end

    resources :answers do
      member do
        post :publish_hidden
        post :subscribe_answers
      end
    end

    resources :questions do
      member do
        post :to_downpayment
        post :publish_hidden
        post :cancel
        post :reopen
        patch :refine_reward
        get :my_favorite_questions
      end
      collection do
        get :invitated_questions
      end
    end

    resources :users do
      member do
        get :new_image
        get :create_image
        get :new_profile
        get :edit_profile
        put :update_profile
        get :show_profile
        get :index_profile
        get :my_questions_answers
        get :wallet
        # add withdraw actions
        get :withdraw_edit
        post :withdraw_change
        get :deposit_edit
        post :deposit_change
        get :exhibition_profile
        get :my_subscriptions
        # 显示我的关注
        get :follow_show
        post :submit_application
        post :add_tags
        get :reply
      end

      collection do
        get :replyers
        get :show_profile
      end
    end

    resources :follows, only: %i(like unlike) do
      member do
        post :like
        post :unlike
      end
    end
  end

  # namespace for admin
  namespace :admin do
    resources :users do
      member do
        post :change_to_admin
        post :change_to_user
        post :approved
      end
    end

    resources :questions do
      member do
        post :hide
        post :publish
      end
    end

    resources :answers do
      member do
        post :hide
        post :publish
      end
    end

    resources :admins do
      collection do
        get :bill
      end
    end

    resources :tags
  end

  # 站内信
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  # vote功能
  namespace :vote do
    # 对answer的vote
    resources :vote_answers, only: %i(like,like_cancel,unlike,unlike_cancel) do
      member do
        post :like
        post :unlike
      end
    end
  end
end

app/views/common/_admin_sidebar.html.erb
<div class="col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="<%= 'active' if controller?('admin/admins') && action?('index') %>"><%= link_to("后台首页", admin_admins_path) %></li>
    <li class="<%= 'active' if controller?('admin/questions') %>"><%= link_to("问题管理", admin_questions_path) %></li>
    <li class="<%= 'active' if controller?('admin/answers') %>"><%= link_to("答案管理", admin_answers_path) %></li>
    <li class="<%= 'active' if controller?('admin/users') %>"><%= link_to("用户管理", admin_users_path) %></li>
    <li class="<%= 'active' if controller?('admin/admins') && action?('bill') %>"><%= link_to("交易管理", bill_admin_admins_path) %></li>
    <li class="<%= 'active' if controller?('admin/tags') %>"><%= link_to("标签管理", admin_tags_path) %></li>
  </ul>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key, value| %>
  <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= value %>
  </div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<div class="navbar footer-bg">

    <div class="navbar-header col-md-4 col-md-offset-4" style="text-align:center">
      <a class="footer-font" href="/">
        <span><%= image_tag("/Site_Logo.png", width: '67px', alt:"m.com", class:"public-logo") %></span>
        <span style="margin:0px 3px">|</span>
        <span>邀约学霸，实现名校梦想</span>
      </a>
    </div>

    <div class="navbar-header col-md-6 col-md-offset-3 footer-font-list" style="text-align:center">
        <br />
        <span class=""><i class="fa fa-envelope-o" aria-hidden="true"></i>
        <%= link_to("Talent8.us@gmail.com", "mailto:talent8.us@gmail.com", class:"footer-font-list") %></span>
        <!-- <%= link_to("About us",about_guides_path,class:"footer-font-list") %>
        <%= link_to("Contact us",contact_guides_path,class:"footer-font-list") %> -->
        <%= link_to("FAQ",faq_guides_path,class:"footer-font-list") %>
    </div>
    <div class="navbar-header col-md-6 col-md-offset-3 footer-font-copyright">
      <br />
      Copyright ©2016 Talent8
    </div>

</div>

app/views/common/_footer_index.html.erb
<footer class="navbar footer-index-bg">

    <div class="navbar-header col-md-4 col-md-offset-4" style="text-align:center">
      <a class="footer-font" href="/">
        <%= image_tag("/Site_Logo.png", width: '67px', alt:"m.com", class:"public-logo") %>
        <span style="margin:0px 3px">|</span>
        <span style="color:#FFF;letter-spacing: 3px;">邀约学霸，实现名校梦想</span>

      </a>
    </div>

    <div class="navbar-header col-md-6 col-md-offset-3 footer-font-list" style="text-align:center">
        <br />
        <span class=""><i class="fa fa-envelope-o" aria-hidden="true"></i>
        <%= link_to("Talent8.us@gmail.com", "mailto:talent8.us@gmail.com", class:"footer-font-list") %></span>
        <!-- <%= link_to("About us", about_guides_path ,class:"footer-font-list") %> -->
        <!-- <%= link_to("Contact us", contact_guides_path ,class:"footer-font-list") %> -->
        <%= link_to("FAQ", faq_guides_path ,class:"footer-font-list") %>
    </div>
    <div class="navbar-header col-md-6 col-md-offset-3 footer-font-copyright">
      <br />
      <span style="letter-spacing: 2px;">Copyright ©2016 Talent8</span>
    </div>


</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-bg" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped fro better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= show_profile_account_user_path(current_user) unless current_user.nil?%>" >
        <%= image_tag("/Site_Logo.png", width: '90px', alt:"m.com", class:"public-logo") %>
      </a>
    </div>
    <!-- Collect the nav links,forms,and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
           <li><%= link_to("注册", new_user_registration_path) %> </li>
           <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
          <li> <%= link_to(" 首页", show_profile_account_user_path(current_user), class:"navbar-font-index") %></li>
          <li class="nav-item btn-group" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
            <a class="dropdown-toggle nav-link navbar-font-index" type="button" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">

            </div>
          </li>

           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               <%= render_head_image_30(current_user) %>
               Hi, <%= current_user.name %>
               <b class="caret"></b>
             </a>

             <ul class="dropdown-menu">
                 <% if current_user.admin? %>
                   <li><%= link_to("管理者后台",admin_admins_path)%></li>
                 <% else %>
                    <li><%= active_link_to " 我的关注", follow_show_account_user_path(current_user),class: "fa fa-heart-o" %></li>
                    <li><%= active_link_to " 我的文章", account_blogs_path, class: "fa fa-pencil-square-o" %></li>
                    <li><%= active_link_to " 我的兴趣标签", account_tags_path, class: "fa fa-tag" %></li>
                    <hr />
                    <li><%= active_link_to " 我偷听的回答", my_subscriptions_account_user_path(current_user),class: "fa fa-headphones" %></li>
                    <li><%= active_link_to " 我的问题与答案", my_questions_answers_account_user_path(current_user), class: "fa fa-comments-o" %></li>
                    <li><%= active_link_to " 被邀请回答的问题", invitated_questions_account_questions_path, class: "fa fa-diamond" %></li>
                    <hr />
                    <li><%= active_link_to " 个人资料", exhibition_profile_account_user_path(current_user),class: "fa fa-user" %></li>
                    <li><%= active_link_to " 我的钱包", wallet_account_user_path(current_user), class: "fa fa-money" %></li>
                 <%end %>

                 <li class="divider"> </li>
                 <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
             </ul>
           </li>
         <% end %>
      </ul>
      <%= render "common/search_bar_nav" %>
    </div>
    <!-- /.navbar-collapse -->
  <div>
  <!-- /.container-fluid -->
</nav>

app/views/common/_navbar_index.html.erb
<nav class="navbar navbar-default col-md-12 col-sm-12 col-xs-12 navbar-index-bg" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped fro better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/" style="color:#FFF">OnlineAs</a>
    </div>

    <!-- Collect the nav links,forms,and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if !current_user %>
           <li><%= link_to("注册", new_user_registration_path) %> </li>
           <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>

          <li class="nav-item btn-group" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
            <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">

            </div>
          </li>

           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= render_head_image_30(current_user) %>
               Hi!, <%= current_user.email %>
               <b class="caret"></b>
             </a>

             <ul class="dropdown-menu">
                 <% if current_user.admin? %>
                   <li><%= link_to("管理者后台",admin_admins_path)%></li>
                 <% else %>
                   <li> <%= link_to("首页", show_profile_account_user_path(current_user)) %></li>
                 <%end %>
                 <li class="divider"> </li>
                 <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
             </ul>
           </li>
         <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  <div>
  <!-- /.container-fluid -->
</nav>

app/views/common/_search_bar_nav.html.erb
<div class="navbar-form navbar-left" role="search">
  <%= form_tag search_questions_path, method: :get  do %>
	<div class="input-group">
		<input type="text" class="form-control" name="query_string" value="<%= params[:query_string] %>" placeholder="搜索／搜索关键字...">
		<span class="input-group-btn">
			<button type="reset" class="btn btn-default">
				<span class="glyphicon glyphicon-remove">
					<span class="sr-only">Close</span>
				</span>
			</button>
			<button type="submit" class="btn btn-default">
				<span class="glyphicon glyphicon-search">
					<span class="sr-only">Search</span>
				</span>
			</button>
		</span>
	</div>
  <% end %>
</div>